### ISSUE TITLE
The server stops after iteration 1 (after a few hundred milliseconds)

### ISSUE THREAD

**Issue by remcollier** [bold-benchmark/bold-server#18]
Hi,

I downloaded the latest release (0.1.0); ran it and managed to get the index.html page displaying.

I send the PUT command to start the simulation, but when I try:

http://localhost:8080/sim

I get a 404 error.

Not sure what I am doing wrong...

Many thanks,

Rem

**Comment by vcharpenay** [comment]
Thank you for reporting the issue.

Did you start the simulation via the form in `index.html`? If you are on Linux, can you try the following command and copy-paste the result?

```sh
curl -v -X "PUT" -H "Content-Type: text/turtle" --data-binary @data/sim.ttl http://localhost:8080/sim
```

**Comment by remcollier** [comment]
Sorry - running it on Windows 10 (Cmd Shell) - will try it on linux

**Comment by remcollier** [comment]
Just realised I still have git bash installed - here is the output

$ curl -v -X "PUT" -H "Content-Type: text/turtle" --data-binary @data/sim.ttl http://localhost:8080/sim
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1:8080...
* Connected to localhost (::1) port 8080 (#0)
> PUT /sim HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.77.0
> Accept: */*
> Content-Type: text/turtle
> Content-Length: 354
>
} [354 bytes data]
* Mark bundle as not supporting multiuse
< HTTP/1.1 201 Created
< Date: Mon, 28 Jun 2021 16:43:25 GMT
< Content-Length: 0
< Server: Jetty(9.4.28.v20200408)
<
100   354    0     0  100   354      0   1096 --:--:-- --:--:-- --:--:--  1095
* Connection #0 to host localhost left intact

**Comment by remcollier** [comment]
Also, the output from Edge Developer Tools was:

Request URL: http://localhost:8080/sim
Request Method: PUT
Status Code: 201 Created
Remote Address: [::1]:8080
Referrer Policy: strict-origin-when-cross-origin
Content-Length: 0
Date: Mon, 28 Jun 2021 16:44:53 GMT
Server: Jetty(9.4.28.v20200408)
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,fr;q=0.8
Connection: keep-alive
Content-Length: 310
Content-Type: text/turtle
Host: localhost:8080
Origin: http://localhost:8080
Referer: http://localhost:8080/index.html
sec-ch-ua: " Not;A Brand";v="99", "Microsoft Edge";v="91", "Chromium";v="91"
sec-ch-ua-mobile: ?0
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.59
@prefix : <http://ti.rw.fau.de/sim#>  .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@base <http://127.0.1.1:8080/> .

<sim> :initialTime "2020-05-21T08:00:00Z"^^xsd:dateTime ;
      # in ms (corresponds to simulated time, not real execution time)
      :timeslotDuration 60000 ;
      :iterations 1440 .

**Comment by remcollier** [comment]
The server log output:

[qtp1595212853-35] INFO de.fau.wintechis.sim.SimulationEngine - Initializing simulation run...
[qtp1595212853-35] INFO de.fau.wintechis.sim.SimulationEngine - Simulation ready: 4311 resources, 44789 quads in dataset.
[qtp1595212853-35] INFO de.fau.wintechis.sim.SimulationEngine - Simulation running...
[Timer-2] INFO de.fau.wintechis.sim.SimulationEngine - Simulation run done. Replaying simulation...
[Timer-2] INFO de.fau.wintechis.sim.SimulationEngine - Replaying iteration 0...
[Timer-2] INFO de.fau.wintechis.sim.SimulationEngine - Done 49904 insertions, 321 deletions.
[Timer-2] INFO de.fau.wintechis.sim.SimulationEngine - Executed query in 3 ms.
[Timer-2] INFO de.fau.wintechis.sim.SimulationEngine - Executed query in 1 ms.
[Timer-2] INFO de.fau.wintechis.sim.SimulationEngine - Executed query in 0 ms.
[Timer-2] INFO de.fau.wintechis.sim.SimulationEngine - Replaying iteration 1...
[Timer-2] INFO de.fau.wintechis.sim.SimulationEngine - Done 0 insertions, 0 deletions.
[Timer-2] INFO de.fau.wintechis.sim.SimulationEngine - Executed query in 2 ms.
[Timer-2] INFO de.fau.wintechis.sim.SimulationEngine - Executed query in 2 ms.
[Timer-2] INFO de.fau.wintechis.sim.SimulationEngine - Executed query in 0 ms.
[Timer-2] INFO de.fau.wintechis.sim.SimulationEngine - Stored interaction counts/times to interactions.tsv.
[Timer-2] INFO de.fau.wintechis.sim.SimulationEngine - Replay done.
[Timer-2] INFO de.fau.wintechis.sim.SimulationEngine - Results written to file(s). Cleaning resources...
[Timer-2] INFO de.fau.wintechis.sim.SimulationEngine - Simulation engine configured. Current configuration: (single updates) [sim-init.rq, query/init-sim-td.rq, query/init-sim-illuminance.rq, query/init-sim-occupancy.rq]; (continuous updates) [sim.rq, query/update-sim-actions.rq, query/update-sim-reactions.rq]; (queries) [query/sim-occupancy.rq, query/sim-illuminance.rq, query/sim-outside-illuminance.rq]; (dump pattern) null.
[Timer-2] INFO de.fau.wintechis.sim.SimulationEngine - Waiting for agent's start command...

**Comment by vcharpenay** [comment]
after a debugging session, we found the problem. I'll document it here in case other users face the same problem.

The problem is that the server stops after iteration 1: it fails to find a number of iterations in resource `sim` and then behaves as if `sim` had been deleted. In fact, `sim` exists but under the wrong URI. For instance, the server could contain the following RDF graph (TriG format):

```
<http://172.23.208.1:8080/sim> {
  <http://127.0.1.1:8080/sim>
    :initialTime "2020-05-21T08:00:00Z"^^xsd:dateTime;
    :timeslotDuration 60000;
    :iterations 1440 .
}
```

where the resource name has IP `172.23.208.1` but the triples that where `PUT`ted to the resource have IP `127.0.1.1`.

**Possible cause**: the network interface of the underlying OS exposes a non-localhost IP to the JVM, which makes the server wrongly resolve relative URIs.

**Solution**: add a hard-coded `@base` declaration in the Turtle payload that is `PUT`ted to start the simulation. E.g.:

```http
PUT /sim HTTP/1.1
Content-Type: text/turtle

@prefix : <http://ti.rw.fau.de/sim#>  .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@base <http://172.23.208.1:8080/> .
<sim>
    :initialTime "2020-05-21T08:00:00Z"^^xsd:dateTime;
    :timeslotDuration 60000;
    :iterations 1440 .
```
