### ISSUE TITLE
Issue with media type matching

### ISSUE THREAD

**Issue by remcollier** [bold-benchmark/bold-server#19]
Bold Server assumes a single media type is passed in the HTTP request. 

Apache Jena passes multiple media types:

Bold server matches types based on this code:

```
Accept:text/turtle,application/n-triples;q=0.9,application/rdf+xml;q=0.7,application/trig,application/n-quads;q=0.9,application/ld+json;q=0.8,*/*;q=0.5
```

This results in a 406 error from the bold server...

**Comment by vcharpenay** [comment]
thanks for the report. I've added a better content negotiation function (this was a ` TODO` in the code). Could you try again with the latest version (c7d354e4c588a9ef005190696b80360ceec00a82)?
