### ISSUE TITLE
text/turtle MediaType

### ISSUE THREAD

**Issue by remcollier** [bold-benchmark/bold-server#21]
We would like to be able to use text/turtle media type.  This can be achieved by adding the following format to the static initialization block in RDFValueFormats.java:

`
formats.add(RDFFormat.TURTLE);
`

**Comment by vcharpenay** [comment]
What is the unexpected behavior you'd like to be fixed? You should indeed be able to do that already. 

When the simulation is running, the server should be able to serve Turtle. The class `RDFValueFormats` is only intended for resources that have a non-RDF representation.

If you look at `GraphStoreHandler.getFormatForMediaType()` ([l. 174](https://github.com/bold-benchmark/bold-server/blob/master/src/main/java/org/bold/gsp/GraphStoreHandler.java#L174)), you'll see that the method first tests if RDF4J recognizes the input media type. Only if it doesn't, the `RDFValueFormats` class is used.

**Comment by remcollier** [comment]
okay - will try again with a new download of the server.  This may have arisen in attempts to overcome the issues with conneg, the code seemed to reach one of the methods in the RDFValueFormats class.

**Comment by remcollier** [comment]
checked & agreed that the change is not needed.
